[package]
name = "rarc_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.13.3"
bitflags = "2.4.2"
szs = "0.3.4"
